### ISSUE TITLE
Install didn't work for me.

### ISSUE THREAD

**Issue by geneorama** [Sleepingwell/DjangoRpyDemo#6]
I'm a beginner with Ubuntu and I've never gotten RPy to work before, so I tired this (it seemed simple), but I got an error that I don't understand.

Can you offer any advice?  I think everything is installed correctly, although I had to install pip. 

![Capture](https://f.cloud.github.com/assets/1392068/125550/52717c7c-6f18-11e2-98c6-73221866b167.PNG)

Also, this command fails:
`sudo ln -s /usr/lib/R/lib/libR.so`
It says that the shortcut already exists (I'm assuming that's a good thing).

**Comment by Sleepingwell** [comment]
The error is telling you that you don't have the package rpy2.robjects. This is most likely because you don't have rpy2 installed.

The easiest way to check whether or not you do would be to start a python session (by typing "python" at a command prompt), then typing the line that is failing - i.e.

> > > from rpy2.robjects import globalenv as globalEnv

If that gives an error, then you might try typing (from the command prompt - not within the Python console):

sudo pip install rpy2

to install rpy2, but you probably did that anyway... didn't you? If that works and you still get your error, then I'm out of suggestions and you may have to resort asking on an Ubuntu forum or the rpy mailing list.

Note that I just fired up a virgin ubuntu 64 vm and followed the instructions in the README file (along with installing python, pip, gcc, ...) and it all worked (not that this helps you though - but it is encouraging!)

Hope that helps,
Simon

**Comment by geneorama** [comment]
Thank you for responding.  I'm sure it's user error on my part since others
never seem to have the same problem...

You're right, rpy2 wasn't installed.  So, I tried installing rpy2 again,
but that failed (I probably didn't realize it failed the first time).

I started a "virgin" Ubuntu instance and tried again, but got the same
error.

I can't imagine how we could get different results, but I've had similar
problems any time I've tried doing anything in Ubuntu.  It seems mysterious
that these things work for everyone else, but not for me!  I must be doing
something fundamentally wrong. I thought the problem was my 32 bit machine,
but now that I have a new 64 bit machine, that is obviously not the
problem!  Also, I tried updating all the software.

Thanks for your suggestions. The problem seems to definitely be with Rpy2.

It's probably obvious to most of your readers, but may I suggest that you
add this line to your readme:
'sudo apt-get install pip'

I think you need to install pip on any fresh install of ubuntu, right?

By the way, tried this on  a friend's mac and it worked perfectly (of
course).  It ran natively using OSX 10.6.8.

Thanks, I'm going to shelve this for now, I'll probably look into this
again later and check with the Rpy2 documentation.

**Comment by Sleepingwell** [comment]
No worries, and good luck with getting on top of Ubuntu!
